### ISSUE TITLE
BUG: Player get's stuck on the right end of all of the platforms

### ISSUE THREAD

**Issue by mattheasboelter** [TARDIS-Maker/The_Game_Where_You_Don-t_Know_Anything#1]
When moving the player to the right on all of the platforms, it gets stuck before the end of it.

When negetive scaling on the X axis to check if it was an issue with the platforms, the player still got stuck.

Tested on both master and player_refactor

**Comment by someonewithpc** [comment]
Appears to be fixed by  3ed07e9
